"""Add active boost tracking columns

Revision ID: 5eb306ab832e
Revises: 6067d21c0b65
Create Date: 2025-11-05 22:38:59.055677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb306ab832e'
down_revision: Union[str, Sequence[str], None] = '6067d21c0b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('active_contributions', sa.Integer(), nullable=False))
    op.add_column('threads', sa.Column('boost_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'boost_expires_at')
    op.drop_column('threads', 'active_contributions')
    # ### end Alembic commands ###
