"""add_kyc_initiated_at_field

Revision ID: 6f0f1b635f33
Revises: e0f6dc69c234
Create Date: 2025-11-03 09:48:44.241662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0f1b635f33'
down_revision: Union[str, Sequence[str], None] = 'e0f6dc69c234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_initiated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_initiated_at')
    # ### end Alembic commands ###
