"""add_listings_table

Revision ID: 801fedbbff55
Revises: 5eb306ab832e
Create Date: 2025-11-07 23:51:15.119514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '801fedbbff55'
down_revision: Union[str, Sequence[str], None] = '5eb306ab832e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=True),
    sa.Column('seller_location', sa.String(length=100), nullable=True),
    sa.Column('seller_verified', sa.Boolean(), nullable=False),
    sa.Column('shipping_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=True),
    sa.Column('ownership_proof_url', sa.Text(), nullable=True),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_index(op.f('ix_listings_listing_type'), 'listings', ['listing_type'], unique=False)
    op.create_index(op.f('ix_listings_thread_id'), 'listings', ['thread_id'], unique=False)
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_thread_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_listing_type'), table_name='listings')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
