"""add_kyc_verification_fields

Revision ID: e0f6dc69c234
Revises: e4c36078732a
Create Date: 2025-11-03 01:48:01.581408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f6dc69c234'
down_revision: Union[str, Sequence[str], None] = 'e4c36078732a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add kyc_status with server default for existing rows
    op.add_column('users', sa.Column('kyc_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('users', sa.Column('kyc_session_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))

    # Remove server default after migration (we want app-level default)
    op.alter_column('users', 'kyc_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_verified_at')
    op.drop_column('users', 'kyc_session_id')
    op.drop_column('users', 'kyc_status')
    # ### end Alembic commands ###
