"""add_user_profile_statistics

Revision ID: e4c36078732a
Revises: 735774342215
Create Date: 2025-11-02 22:34:01.964895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c36078732a'
down_revision: Union[str, Sequence[str], None] = '735774342215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults for existing rows
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('rating_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('total_listings', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('completed_deals', sa.Integer(), nullable=False, server_default='0'))

    # Remove server defaults after initial migration (we want app-level defaults)
    op.alter_column('users', 'rating', server_default=None)
    op.alter_column('users', 'rating_count', server_default=None)
    op.alter_column('users', 'total_listings', server_default=None)
    op.alter_column('users', 'completed_deals', server_default=None)

    op.alter_column('users', 'clerk_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'clerk_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'completed_deals')
    op.drop_column('users', 'total_listings')
    op.drop_column('users', 'rating_count')
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
